"""
batch/export_candidate.py
=========================
Materialize an optimized design into an actual Robot project file (.rtd)
so a person can open it and look at it - not just read numbers from runs.db.

export_candidate()       build + solve one design_vars, save the project.
export_best_from_run()   pick a frontier candidate from a completed run and
                         export it (default: the lightest passing one).

Design / scope notes
--------------------
* Defaults to HeadlessSession(visible=True) - the whole point is a human
  opens the saved model. `session_factory` lets offline tests inject a
  fake double (same pattern as run_batch).
* Applies design_vars EXACTLY like runner._evaluate_candidate does
  (apply_to_geometry -> clear_structure -> build_from_spec ->
  validate_stability -> solve_all), so the model you open is the same
  model the optimizer scored. Mechanism detection is honored - an
  unstable design is never exported as if it solved.
* project="3D" per the live-verified 2026-08-22 finding (README "Known
  issues"): project="2D" specs solve to a structurally invalid frame on
  this Robot build. If a spec still carries "2D", a loud warning is
  logged instead of silently saving an invalid model.
* RobotBridge.save_project() is reused as-is (it appends .rtd and creates
  parent folders) - wired in, not reimplemented.
"""
from __future__ import annotations

import json
import logging
import os
from typing import Any, Callable, Dict, Optional

from batch.design_space import DesignSpace
from batch.headless_driver import HeadlessSession, MechanismError
from batch.pareto import compute_pareto_frontier
from batch.storage import Storage

logger = logging.getLogger("structural_copilot.batch.export_candidate")


def export_candidate(
    design_space: DesignSpace,
    design_vars: Dict[str, Any],
    output_path: str,
    eval_case_id: Optional[int] = None,
    session_factory: Optional[Callable[[], Any]] = None,
    visible: bool = True,
) -> str:
    """Build + solve one candidate and save the project to ``output_path``.

    ``design_vars`` may be a full candidate dict (with "group_choices" /
    "sections", as generated by DesignSpace.generate_candidates) or a bare
    {bar_id: section} map - apply_to_geometry handles both, exactly like
    runner._evaluate_candidate.

    Returns the absolute saved path (".rtd" appended when missing).
    """
    # Apply design_vars exactly as runner._evaluate_candidate does.
    geometry = design_space.apply_to_geometry(design_vars)
    proj = str(geometry.get("project") or "3D")
    if proj.lower() == "2d":
        logger.warning(
            "export_candidate: spec uses project='2D' - on this Robot build "
            "'2D' specs solve to a structurally INVALID frame (columns carry "
            "zero force, beam not in equilibrium - see README 'Known issues', "
            "2026-08-22). The saved model may be wrong; prefer project='3D'.")

    factory = session_factory or (lambda: HeadlessSession(visible=visible))
    session = factory()
    session.connect()
    try:
        session.clear_structure(proj)
        session.build_from_spec(geometry)
        stability = session.validate_stability()
        if not stability.get("ok", True):
            raise MechanismError(stability.get("message", "mechanism detected"))
        session.solve_all(design_space.analysis_types)
        session.bridge.save_project(output_path)
    finally:
        try:
            session.close()
        except Exception as exc:  # noqa: BLE001
            logger.warning("Session close error: %s", exc)

    saved = os.path.abspath(output_path)
    if not saved.lower().endswith(".rtd"):
        saved += ".rtd"
    logger.info("Exported candidate to %s (project=%s).", saved, proj)
    return saved


def export_best_from_run(
    run_id: int,
    output_path: str,
    frontier_index: int = 0,
    db_path: Optional[str] = None,
    eval_case_id: Optional[int] = None,
    session_factory: Optional[Callable[[], Any]] = None,
    visible: bool = True,
) -> str:
    """Export one candidate from a completed run's Pareto frontier.

    Pulls the frontier via pareto.compute_pareto_frontier (hard pass_fail
    gate unchanged), sorts by weight ascending, picks the
    ``frontier_index``-th candidate (0 = lightest passing one, the default),
    and calls export_candidate with its design_vars.

    Returns the absolute saved path.
    """
    storage = Storage(db_path=db_path)
    run = storage.get_run(int(run_id))
    if run is None:
        raise ValueError(f"run {run_id} does not exist in storage.")
    try:
        spec = json.loads(run.get("spec_json") or "{}")
    except (TypeError, ValueError) as exc:
        raise ValueError(f"run {run_id} has an unreadable spec_json: {exc}")

    df = storage.get_all_results(int(run_id))
    frontier = compute_pareto_frontier(df)
    if frontier.empty:
        raise ValueError(
            f"run {run_id} has no candidates passing the design constraint "
            f"- nothing to export.")
    frontier = frontier.sort_values("weight_kg", kind="mergesort")
    n = len(frontier)
    if frontier_index < 0 or frontier_index >= n:
        raise ValueError(
            f"frontier_index {frontier_index} out of range - frontier has "
            f"{n} candidates.")

    chosen = frontier.iloc[int(frontier_index)]
    design_vars = json.loads(chosen["design_vars_json"])
    logger.info(
        "Exporting run %s frontier[%d]: weight=%.1f kg, max_utilization=%s.",
        run_id, frontier_index, float(chosen["weight_kg"]),
        chosen.get("max_utilization"))
    design_space = DesignSpace(spec)
    return export_candidate(
        design_space, design_vars, output_path, eval_case_id=eval_case_id,
        session_factory=session_factory, visible=visible)
